language: android
jdk: oraclejdk8
sudo: required
before_install:
  - nvm install 12
  - node --version
  - npm install
  - gem install bundler
  - bundle install
  - yes | sdkmanager "platforms;android-29"


  
android:
  components:
    - android-29
    - tools
    - platform-tools

before_script:
 - chmod +x android/gradlew

script: fastlane android build